version: "3.9"

services:
  strapi:
    image: strapi/strapi
    container_name: strapi-app
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: "key1,key2,key3,key4"
      API_TOKEN_SALT: somerandomsalt
      ADMIN_JWT_SECRET: somesecretjwt
      TRANSFER_TOKEN_SALT: transfersecret
      ENCRYPTION_KEY: encryptionsecret
      DATABASE_CLIENT: sqlite
    ports:
      - "1337:1337"
    volumes:
      - ./app:/srv/app
