<<<<<<< HEAD
version: "3"
services:
  strapi:
    build: .
    ports:
      - "1337:1337"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
=======
version: "3.9"

networks:
  strapi-net:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: strapi-postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
      POSTGRES_DB: strapidb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strapi-net

  strapi:
    image: strapi/strapi
    container_name: strapi-app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapidb
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - strapi-net

  nginx:
    image: nginx:alpine
    container_name: strapi-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - strapi
    networks:
      - strapi-net

volumes:
  postgres_data:
>>>>>>> 7309fed (Docker Networking)
